
buildscript {
    ext.kotlin_version = '1.8.22'
    ext.compose_version = '1.4.3'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    tools = [
            minSdk      : 21,
            targetSdk   : 31,
            compileSdk  : 31,
            versionName: '3.2.0-beta.3'
    ]
}
