apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion rootProject.tools.compileSdk

    defaultConfig {
        minSdkVersion rootProject.tools.minSdk
        targetSdkVersion rootProject.tools.targetSdk
        versionCode 1
        versionName "${rootProject.tools.versionName}"
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.4.8'
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

}

dependencies {
    implementation 'androidx.core:core:1.7.0'
    api 'com.github.mhiew:pdfium-android:1.9.2'
    
    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    
    // Compose
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.foundation:foundation:$compose_version"
    implementation "androidx.compose.runtime:runtime:$compose_version"
}

// Maven Publishing
ext {
    PUBLISH_GROUP_ID = 'com.github.mhiew'
    PUBLISH_VERSION = "${rootProject.tools.versionName}"
    PUBLISH_ARTIFACT_ID = 'android-pdf-viewer'
}

apply from: "${rootProject.projectDir}/android-pdf-viewer/publish-mavencentral.gradle"