apply plugin: 'com.android.library'

android {
    namespace 'com.github.barteksc.pdfviewer'
    compileSdkVersion rootProject.tools.compileSdk

    defaultConfig {
        minSdkVersion rootProject.tools.minSdk
        targetSdkVersion rootProject.tools.targetSdk
        versionCode 1
        versionName "${rootProject.tools.versionName}"
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

}

dependencies {
    implementation 'androidx.core:core:1.7.0'
    api 'com.github.mhiew:pdfium-android:1.9.2'
}

// Maven Publishing
ext {
    PUBLISH_GROUP_ID = 'com.github.hisetu'
    PUBLISH_VERSION = "${rootProject.tools.versionName}-zoomfix1"
    PUBLISH_ARTIFACT_ID = 'android-pdf-viewer'
    PUBLISH_REPOSITORY_NAME = 'GitHubPackages'
    PUBLISH_REPOSITORY_URL = 'https://maven.pkg.github.com/hisetu/AndroidPdfViewer'
}

apply from: "${rootProject.projectDir}/android-pdf-viewer/publish-mavencentral.gradle"
